language: python

python:
  - 3.6

install:
    yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots;
    yes | sudo add-apt-repository ppa:gstreamer-developers/ppa;
    sudo apt-get update;
    sudo apt-get install python3-pip;
    sudo pip3 install python3-git;

before_script:
    export DISPLAY=:99.0;
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX;
    export PYTHONPATH=$PYTHONPATH:$(pwd);
    mkdir -p ~/.config;

script:
    python3 main.py Testprogram 1.0.0 copyright ./ -repo http://github.com/Author/Project -author AuthorName -mail kivydevelopment@gmail.com -site http://project_site;
    cd ./Testprogram;
    python3 -m unittest test/test_app.py;
